joint_names: ['shoulder_pan_joint', 'shoulder_lift_joint', 'elbow_joint','wrist_1_joint', 'wrist_2_joint', 'wrist_3_joint']

# back side positions
home: [[0.797, -1.54, -2.016, 0.475, 1.568, -1.542]]
ablegen: [[0.828, -2.55, -2.248, 1.747, 1.571, -1.542]]
regal: [[2.47, -1.379, -1.408, -0.286, 1.503, -1.49]]

