# node from which initial footprint is read
footprint_source: /local_costmap_node/costmap

# 
robot_base_frame: /base_link
# frames to check for footprint adjustment
frames_to_check: /sdh_tip_link /arm_left_6_link /arm_left_4_link /arm_right_6_link /arm_right_4_link
